M48
; DRILL file {KiCad 8.0.4} date 2025-07-27T15:22:33-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-07-27T15:22:33-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.9213Y-3.0512
X4.9213Y-4.626
X6.4921Y-4.626
X6.4961Y-3.0512
M30
