M48
; DRILL file {KiCad (6.0.9)} date Tue May 21 19:31:50 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-21T19:31:50-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.9173Y-3.0906
X4.9173Y-4.5866
X6.5Y-3.0906
X6.5Y-4.5866
T0
M30
